# Generated by Django 4.2.26 on 2025-12-02 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('ingredients', models.TextField(help_text='Enter each ingredient, separated by a comma')),
                ('cooking_time', models.IntegerField(help_text='In minutes')),
                ('difficulty', models.CharField(blank=True, max_length=20)),
                ('instructions', models.TextField()),
            ],
        ),
    ]
